import { describe, expect, it } from "vitest";
import { App } from "aws-cdk-lib";
import { Match, Template } from "aws-cdk-lib/assertions";
import { WatametaStack } from "../lib/watameta-stack.js";
import { developmentConfig, productionConfig } from "../lib/config.js";

function synth(config: typeof developmentConfig) {
  const app = new App();
  const stack = new WatametaStack(app, "TestStack", { config });
  return Template.fromStack(stack);
}

describe("WatametaStack", () => {
  it("creates one VPC with public, app, and isolated subnet tiers", () => {
    const template = synth(developmentConfig);

    template.resourceCountIs("AWS::EC2::VPC", 1);
    // 2 AZs x 3 tiers (public / app / data)
    template.resourceCountIs("AWS::EC2::Subnet", 6);
  });

  it("puts RDS only in the isolated subnet tier, encrypted, not publicly accessible", () => {
    const template = synth(developmentConfig);

    template.hasResourceProperties("AWS::RDS::DBInstance", {
      Engine: "postgres",
      StorageEncrypted: true,
      PubliclyAccessible: false,
    });
  });

  it("only allows the app security group to reach RDS on 5432", () => {
    const template = synth(developmentConfig);

    template.hasResourceProperties("AWS::EC2::SecurityGroupIngress", {
      FromPort: 5432,
      ToPort: 5432,
      IpProtocol: "tcp",
    });
  });

  it("creates the four application secrets plus RDS's own generated credentials secret", () => {
    const template = synth(developmentConfig);

    // 4 application secrets (DATABASE_URL, AUTH_SECRET, AUTH_GOOGLE_ID,
    // AUTH_GOOGLE_SECRET) + 1 auto-generated by rds.Credentials.
    template.resourceCountIs("AWS::SecretsManager::Secret", 5);

    for (const description of [
      Match.stringLikeRegexp("postgres://.*watameta"),
      Match.stringLikeRegexp("AUTH_SECRET"),
      Match.stringLikeRegexp("AUTH_GOOGLE_ID"),
      Match.stringLikeRegexp("AUTH_GOOGLE_SECRET"),
    ]) {
      template.hasResourceProperties("AWS::SecretsManager::Secret", { Description: description });
    }
  });

  it("wires the ECS task's secrets to DATABASE_URL, AUTH_SECRET, and the Google OAuth credentials", () => {
    const template = synth(developmentConfig);

    template.hasResourceProperties("AWS::ECS::TaskDefinition", {
      ContainerDefinitions: Match.arrayWith([
        Match.objectLike({
          Secrets: Match.arrayWith([
            Match.objectLike({ Name: "DATABASE_URL" }),
            Match.objectLike({ Name: "AUTH_SECRET" }),
            Match.objectLike({ Name: "AUTH_GOOGLE_ID" }),
            Match.objectLike({ Name: "AUTH_GOOGLE_SECRET" }),
          ]),
        }),
      ]),
    });
  });

  it("points the load balancer's health check at /api/health", () => {
    const template = synth(developmentConfig);

    template.hasResourceProperties("AWS::ElasticLoadBalancingV2::TargetGroup", {
      HealthCheckPath: "/api/health",
    });
  });

  it("defines a second task definition for one-off migrations", () => {
    const template = synth(developmentConfig);

    template.resourceCountIs("AWS::ECS::TaskDefinition", 2);
    template.hasResourceProperties("AWS::ECS::TaskDefinition", {
      ContainerDefinitions: Match.arrayWith([
        Match.objectLike({ Command: ["npm", "run", "migrate"] }),
      ]),
    });
  });

  it("sizes development modestly: single task, single NAT gateway, no deletion protection", () => {
    const template = synth(developmentConfig);

    template.resourceCountIs("AWS::EC2::NatGateway", 1);
    template.hasResourceProperties("AWS::ECS::Service", { DesiredCount: 1 });
    template.hasResourceProperties("AWS::RDS::DBInstance", {
      DeletionProtection: false,
      MultiAZ: false,
    });
  });

  it("sizes production for availability: multiple tasks, multiple NAT gateways, deletion protection, Multi-AZ", () => {
    const template = synth(productionConfig);

    template.resourceCountIs("AWS::EC2::NatGateway", 2);
    template.hasResourceProperties("AWS::ECS::Service", { DesiredCount: 2 });
    template.hasResourceProperties("AWS::RDS::DBInstance", {
      DeletionProtection: true,
      MultiAZ: true,
    });
  });

  it("only adds autoscaling for production", () => {
    const dev = synth(developmentConfig);
    const prod = synth(productionConfig);

    expect(dev.findResources("AWS::ApplicationAutoScaling::ScalableTarget")).toEqual({});
    expect(Object.keys(prod.findResources("AWS::ApplicationAutoScaling::ScalableTarget"))).toHaveLength(1);
  });
});
